name: Build

on: [push, pull_request]

permissions:
  contents: write
  issues: write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      -   name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'
            architecture: x64

      -   name: Git checkout for source code analysis
          uses: actions/checkout@v3

      -   name: Install Dependencies
          run: |
            npm ci
      -   name: Cache Node.js modules
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}

      -   name: Run unit tests
          run: |
            npm run test